#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'countApplesAndOranges' function below.
#
# The function accepts following parameters:
#  1. INTEGER s
#  2. INTEGER t
#  3. INTEGER a
#  4. INTEGER b
#  5. INTEGER_ARRAY apples
#  6. INTEGER_ARRAY oranges
#

def countApplesAndOranges(s, t, a, b, apples, oranges):
    ap = 0
    orr = 0

    for m in apples:
        cd = a + m  # Distance of the apple from the apple tree
        if s <= cd <= t:
            ap += 1

    for n in oranges:
        cdo = b + n  # Distance of the orange from the orange tree
        if s <= cdo <= t:
            orr += 1

    return ap, orr

if __name__ == '__main__':
    first_multiple_input = input().rstrip().split()

    s = int(first_multiple_input[0])
    t = int(first_multiple_input[1])

    second_multiple_input = input().rstrip().split()

    a = int(second_multiple_input[0])
    b = int(second_multiple_input[1])

    third_multiple_input = input().rstrip().split()

    m = int(third_multiple_input[0])
    n = int(third_multiple_input[1])

    apples = list(map(int, input().rstrip().split()))
    oranges = list(map(int, input().rstrip().split()))

    result = countApplesAndOranges(s, t, a, b, apples, oranges)
    print(result[0])
    print(result[1])
