#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'diagonalDifference' function below.
#
# The function is expected to return an INTEGER.
# The function accepts 2D_INTEGER_ARRAY arr as parameter.
#

def diagonalDifference(arr):
    # Write your code here
    leftdiagnol = 0
    rightdiagnol = 0
    for i in range(len(arr)):
        leftdiagnol+=arr[i][i] #[0][0]
        rightdiagnol += arr[i][n-1-i] #[0][3-1-0]
    return abs(leftdiagnol - rightdiagnol)

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = []

    for _ in range(n):
        arr.append(list(map(int, input().rstrip().split())))

    result = diagonalDifference(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
