#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'gradingStudents' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts INTEGER_ARRAY grades as parameter.
#




def gradingStudents(grades):
    rounded_grades = []
    for i in grades:
        a = i+2
        b = i+1
        if a%5 == 0 and a>=40:
            rounded_grades.append(a)
        elif b%5 == 0 and b>=40:
            rounded_grades.append(b)
        else:
            rounded_grades.append(i)
    return rounded_grades
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    grades_count = int(input().strip())

    grades = []

    for _ in range(grades_count):
        grades_item = int(input().strip())
        grades.append(grades_item)

    result = gradingStudents(grades)

    fptr.write('\n'.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
