#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'plusMinus' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def plusMinus(arr):
    # Write your code here
    Neg = 0
    Pos = 0
    Zero = 0
    
    for i in range(len(arr)):
        if arr[i]<0:
            Neg+=1
        elif arr[i]>0:
            Pos+=1
        else:
            Zero+=1
    print(Pos/len(arr))
    print(Neg/len(arr))
    print(Zero/len(arr))

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
